config/routes.rb
EnegeryManagement::Application.routes.draw do

  devise_for :admins, :controllers => { :registrations => "registrations", :sessions => "sessions" }    

  resources :halls, :only => [:index, :show]

  resources :admin, :only => [:index]
  resources :tips, :only => [:index]

  namespace :admin do
    resources :tips
    resources :categories do
      member do
        get 'edit_tips'
        put 'update_tips'
      end
    end
  end
  
  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_tips
  has_many :tips, :through => :category_tips
  has_many :settings, :through => :device_categories
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_filter :authenticate_admin!
  layout 'admin'

  def index
    @categories = Category.all
    @tips_by_categories = Tip.tips_by_categories
  end
  
  def show
    @category = Category.find_by_id(params[:id])
    if !@category
      flash[:error] = 'That category does not exist.'
      redirect_to admin_categories_path
    else
      @category_tips = @category.tips
    end
  end

  def new
    @categories = Category.all
  end

  def create
    @category = Category.create params[:category]
    if @category and @category.id
      flash[:notice] = "#{@category.name} was successfully created."
      redirect_to admin_categories_path 
    else
      # Category create failed, redirect back to "new" view
      flash[:error] = "Category creation failed."
      redirect_to new_admin_category_path
    end
  end

  def edit
	@category = Category.find_by_id params[:id]
	@categories = Category.all
  end

  def update
    @category = Category.find_by_id params[:id]
    if @category
      valid_update = @category.update_attributes params[:category]
      if !valid_update
        flash[:error] = "Couldn't update #{@category.name}."
        redirect_to edit_admin_category_path
      else
        flash[:notice] = "#{@category.name} was successfully updated."
        redirect_to edit_tips_admin_category_path @category
      end
    else
      # Couldn't find the category, redirect to the index page with an error
      flash[:error] = "That category does not exist."
      redirect_to admin_categories_path
    end
  end

  def edit_tips
    @category = Category.find_by_id params[:id]
    if @category
      # Fetch the current tips under this category for display
      @all_tips = Tip.all
      @tips = CategoryTip.find_all_by_category_id(params[:id])
    else
      # Couldn't find the category, redirect to the index page with an error
      flash[:error] = "That category does not exist."
      redirect_to admin_categories_path
    end
  end

  def update_tips
    @category = Category.find_by_id params[:id]
    if @category
      if params[:tips]
        # Remove all tips with this category's id.
        CategoryTip.destroy_all :category_id => @category.id
        # Create a new CategoryTip entry for each checked tip
        params[:tips].each do |tip|
          CategoryTip.create :tip_id => tip[0].to_i, :category_id => @category.id
        end
      end
      flash[:notice] = "#{@category.name} tips successfully updated."
      redirect_to admin_category_path @category
    else
      # Couldn't find the category, redirect to the index page with an error
      flash[:error] = "That category does not exist."
      redirect_to admin_categories_path
    end
  end

  def destroy
    @category = Category.find_by_id params[:id]
    if @category
      if @category.destroy
        flash[:notice] = "Category '#{@category.name}' deleted."
        redirect_to admin_categories_path
      else
        flash[:error] = "Sorry, you aren't strong enough to destroy this category."
        redirect_to edit_admin_category_path
      end
    else
      # category was not found
      flash[:error] = "That category does not exist."
      redirect_to admin_categories_path
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<%= form_tag admin_category_path(@category), :method => 'put' do %>
  <%= label_tag :name, 'Name' %>
  <%= text_field :category, 'name' %>

  <br />
  <%= submit_tag 'Update Category', :class => 'btn btn-success' %>
<% end %>

 <%= button_to 'Delete Category', admin_category_path(@category), :method => :delete, :confirm => "Are you sure?", :class => 'btn btn-danger'%>

app/views/admin/categories/edit_tips.html.erb
<%= form_tag update_tips_admin_category_path(@category), :method => 'put' do %>
  <%= label_tag :tips, 'Tips'%>
  <% @all_tips.each do |tip| %>
    <label class="checkbox">
      <%= check_box_tag "tips[#{tip.id}]", 1, @category.tips.include?(tip)%>
      <%= tip.title %>
    </label>
  <% end %>
  <%= submit_tag 'Update tips for this category', :class => 'btn btn-success' %>
<% end %>

app/views/admin/categories/index.html.erb
<a href="/admin/categories/new">
  <button class="btn">
    New Category
  </button>
</a>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th># of Tips in this Category</th>
    </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.name, admin_category_path(category) %></td>
    <td><%= @tips_by_categories[category.name] ? @tips_by_categories[category.name].count : 0 %></td>
  </tr>
  <% end %>
</table>

<a href="/admin/category/new">
  <button class="btn">
    New Category
  </button>
</a>

app/views/admin/categories/new.html.erb
<%= form_tag admin_categories_path, :method => 'post' do %>
  <%= label_tag :title, 'Title' %>
  <%= text_field :category, 'name' %>

  <br />
  <%= submit_tag 'Create category', :class => 'btn btn-success' %>
<% end %>

app/views/admin/categories/show.html.erb
<h3>Title</h3>
<p><%=@category.name%></p>
<a href="<%= edit_admin_category_path(@category) %>" id="edit-tip">
  <button class="btn">Edit</button>
</a>
<br />
<br />
<h3>Tips in this category</h3>
<% if @category_tips.count == 0 %>
	<h5>No tips in this category</h5>
<% else %>
		<table class="table table-striped">
		  <thead>
			<tr>
			  <th>Title</th>
			  <th>Category</th>
			  <th>Content</th>
			</tr>
		  </thead>
		  <tbody>
		  <% @category_tips.each do |tip| %>
		  <tr>
			<td><%= link_to tip.title, admin_tip_path(tip)%></td>
			<td>
			  <% tip.categories.each_index do |i|%>
					<%= tip.categories[i].name %><% if i + 1 != tip.categories.length %>,<% end %>
			  <% end %>
			</td>
			<td><%=tip.content%></td>
		  </tr>
		  <% end %>
		</table>
<% end %>